"""generate_initial_schema

Revision ID: 2926cbd96f0a
Revises: 
Create Date: 2025-06-04 15:20:56.656570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2926cbd96f0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laptops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_api_contact', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_type', sa.String(), nullable=True),
    sa.Column('last_scan_result_message', sa.Text(), nullable=True),
    sa.Column('last_scan_threats_found', sa.Boolean(), nullable=True),
    sa.Column('pending_command', sa.String(), nullable=True),
    sa.Column('command_issue_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laptops_alias_name'), 'laptops', ['alias_name'], unique=True)
    op.create_index(op.f('ix_laptops_hostname'), 'laptops', ['hostname'], unique=True)
    op.create_index(op.f('ix_laptops_id'), 'laptops', ['id'], unique=False)
    op.create_table('scan_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laptop_id', sa.Integer(), nullable=False),
    sa.Column('report_time_on_server', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('client_scan_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('scan_result_message', sa.Text(), nullable=False),
    sa.Column('threats_found', sa.Boolean(), nullable=False),
    sa.Column('threat_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_reports_id'), 'scan_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_reports_id'), table_name='scan_reports')
    op.drop_table('scan_reports')
    op.drop_index(op.f('ix_laptops_id'), table_name='laptops')
    op.drop_index(op.f('ix_laptops_hostname'), table_name='laptops')
    op.drop_index(op.f('ix_laptops_alias_name'), table_name='laptops')
    op.drop_table('laptops')
    # ### end Alembic commands ###
