"""add_pending_scan_type_to_laptops

Revision ID: f5630f027558
Revises: 2926cbd96f0a
Create Date: 2025-06-04 16:58:31.024276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5630f027558'
down_revision: Union[str, None] = '2926cbd96f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptops', sa.Column('pending_scan_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laptops', 'pending_scan_type')
    # ### end Alembic commands ###
