name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]
  # Ermöglicht das manuelle Starten des Workflows über die GitHub UI
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Setzt 'latest' beim Push auf main
            type=raw,value=latest,enable={{is_default_branch}}
            # Nutzt die Versionierung beim Erstellen eines Releases (z.B. v1.0.0 -> 1.0.0)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  upload-client-assets:
    runs-on: ubuntu-latest
    # Führt diesen Job NUR aus, wenn der Workflow durch ein neues Release getriggert wurde
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Version in Script
        run: |
          sed -i 's/\$ClientVersion = ".*"/\$ClientVersion = "${{ github.ref_name }}"/g' client/ScanOpClient.ps1
          sed -i 's/\[string\]\$Version = ""/\[string\]\$Version = "${{ github.ref_name }}"/g' client/install.ps1

      - name: Zip Client Folder
        run: |
          cd client
          zip -r ../ScanOp-Client.zip ./*
          cd ..

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ScanOp-Client.zip

